name: changeflycube
description: A code challenge assignment from Changefly for the part-time internship program.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.6.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/changefly-cube.png"
  image_path_android: "assets/changefly-cube.png"
  image_path_ios: "assets/changefly-cube.png"
  adaptive_icon_background: "#FFFAFAFA"
  adaptive_icon_foreground: "assets/changefly-cube.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
